export const hospedes = [
  {
    id: "1",
    nome: "Yago Belo",
    dataNascimento: "15/02/2000",
    telefone: "993115559",
    email: "yago@email.com",
    cpf: "12345678989",
    pais: "Brasil",
    estado: "Alagoas",
    cidade: "Maceio",
    logradouro: "Rua Brasil Alagoas",
    n: "10",
    bairro: "Centro",
    complemento: "",
  },
  {
    id: "2",
    nome: "Yago Belo",
    dataNascimento: "15/02/2000",
    telefone: "993115559",
    email: "yago@email.com",
    cpf: "12345678989",
    pais: "Brasil",
    estado: "Alagoas",
    cidade: "Maceio",
    logradouro: "Rua Brasil Alagoas",
    n: "10",
    bairro: "Centro",
    complemento: "",
  },
  {
    id: "3",
    nome: "Yago Belo",
    dataNascimento: "15/02/2000",
    telefone: "993115559",
    email: "yago@email.com",
    cpf: "12345678989",
    pais: "Brasil",
    estado: "Alagoas",
    cidade: "Maceio",
    logradouro: "Rua Brasil Alagoas",
    n: "10",
    bairro: "Centro",
    complemento: "",
  },
  {
    id: "4",
    nome: "Yago Belo",
    dataNascimento: "15/02/2000",
    telefone: "993115559",
    email: "yago@email.com",
    cpf: "12345678989",
    pais: "Brasil",
    estado: "Alagoas",
    cidade: "Maceio",
    logradouro: "Rua Brasil Alagoas",
    n: "10",
    bairro: "Centro",
    complemento: "",
  },
];
